FROM bitnami/spark:3.5.0

USER root

# 1) Prépa du dossier Delta (checkpoints) et droits
RUN mkdir -p /delta/_ck/bronze_sport /delta/_ck/elig_gold \
 && chown -R 1001:0 /delta

# 2) Installer curl
RUN apt-get update && apt-get install -y curl


# 4) Installer les dépendances Python
RUN pip install --no-cache-dir pandas openpyxl pyarrow pyyaml confluent-kafka

# 5) Repasser en user non-root pour démarrer Spark
USER 1001
WORKDIR /app

# 6) Copier les scripts
COPY spark_bronze.py spark_gold.py ./