{
 "title": "New dashs",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Spark UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spark\", spark_app=~\"bronze|gold\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Batch / sec",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (spark_app) (\r\n  rate(\r\n    {__name__=~\"spark_.*StreamingQueryListenerBus_Count\", job=\"spark\", spark_app=~\"bronze|gold\"}[1m]\r\n  )\r\n)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Postgres UP",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"postgres\"}\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Debezium – Active / Idle Connections",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_stat_activity_count{datname=\"sportsdb\", application_name=~\"Debezium.*\"}\r\n",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Debezium error",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(debezium_postgres_connector_metrics_NumberOfErroneousEvents{context=\"streaming\"}[5m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retard CDC",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "debezium_postgres_connector_metrics_MilliSecondsBehindSource",
     "legendFormat": "{{__name__}}"
    }
   ]
  }
 ]
}