# monitoring/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'redpanda'
    metrics_path: /public_metrics
    static_configs:
      - targets: ['redpanda:9644']

  - job_name: 'connect'
    # supposez que vous avez exposé JMX via un sidecar JMX exporter sur le port 5556
    metrics_path: /metrics
    static_configs:
      - targets: ['kafka_connect:5556']


  - job_name: 'spark'
    scrape_interval: 5s
    static_configs:
      - targets: ['spark_bronze:4040']
        labels:
          job: 'spark'
          spark_app: 'bronze'
          app_instance: 'bronze_${HOSTNAME}'
      - targets: ['spark_gold:4040']
        labels:
          job: 'spark'
          spark_app: 'gold'
          app_instance: 'gold_${HOSTNAME}'
    metrics_path: /metrics
    scheme: http
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(.*)'
        target_label: __name__
        replacement: 'spark_${1}'

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres_exporter:9187']
    metrics_path: /metrics
    scrape_interval: 15s
